# 敌人类型配置列表，每个元素代表一种类型的敌人
cardTypeConfigs:
  - # 初级弓箭手
    cardType: "arrower"
    rarity: N
    attackPower: 1
    attackRange: 100f
    maxAttackCount: 2
    fireRate: 0.5f
    cardTexture: arrower
    mapTexture: arrower
    stuffTexture: arrowerStuff
    attackTexture: arrow
  - # 白虎战士
    cardType: "whiteTiger"
    rarity: N
    attackPower: 2
    attackRange: 120f
    maxAttackCount: 2
    fireRate: 0.5f
    cardTexture: whiteTiger
    mapTexture: whiteTiger
    stuffTexture: whiteTigerStuff
    attackTexture: whiteAttack
  - # 招财童子
    cardType: "prosperityGirl"
    rarity: S
    attackPower: 0
    attackRange: 1000f
    maxAttackCount: 2
    fireRate: 0.5f
    cardTexture: prosperityGirl
    mapTexture: prosperityGirl
    stuffTexture: prosperityGirlStuff
    attackTexture: whiteAttack
  - # 玄武法师
    cardType: "blackTortoise"
    rarity: S
    attackPower: 1
    attackRange: 100f
    maxAttackCount: 2
    fireRate: 0.5f
    cardTexture: blackTortoise
    mapTexture: blackTortoise
    stuffTexture: blackTortoiseStuff
    attackTexture: blackTortoiseAttack
  - # 朱雀法师
    cardType: "vermilion"
    rarity: S
    attackPower: 1
    attackRange: 100f
    maxAttackCount: 2
    fireRate: 0.5f
    cardTexture: vermilion
    mapTexture: vermilion
    stuffTexture: vermilionStuff
    attackTexture: vermilionAttack
  - # 阴阳师
    cardType: "yys"
    rarity: S
    attackPower: 3
    attackRange: 120f
    maxAttackCount: 2
    fireRate: 0.5f
    cardTexture: yys
    mapTexture: yys
    stuffTexture: yysStuff
    attackTexture: fan
  - # 青龙法师
    cardType: "azureDragon"
    rarity: SR
    attackPower: 3
    attackRange: 120f
    maxAttackCount: 2
    fireRate: 0.5f
    cardTexture: azureDragon
    mapTexture: azureDragon
    stuffTexture: azureDragonStuff
    attackTexture: dragonAttack
  - # 剑士
    cardType: "saber"
    rarity: SR
    attackPower: 5
    attackRange: 120f
    maxAttackCount: 3
    fireRate: 0.5f
    cardTexture: saber
    mapTexture: saber
    stuffTexture: saberStuff
    attackTexture: whiteAttack
  - # 剑仙
    cardType: "swordSaint"
    rarity: SSR
    attackPower: 10
    attackRange: 300f
    maxAttackCount: 3
    fireRate: 0.5f
    cardTexture: swordSaint
    mapTexture: swordSaint
    stuffTexture: swordSaintStuff
    attackTexture: saintSword
  - # 亡灵法师
    cardType: "necromancer"
    rarity: SSR
    attackPower: 5
    attackRange: 200f
    maxAttackCount: 3
    fireRate: 0.5f
    cardTexture: necromancer
    mapTexture: necromancer
    stuffTexture: necromancerStuff
    attackTexture: necromancerAttack