# 敌人类型配置列表，每个元素代表一种类型的敌人
cardTypeConfigs:
  - # 初级弓箭手
    cardType: "arrower"
    rarity: N
    attackPower: 1
    attackRange: 100f
    maxAttackCount: 2
    fireRate: 0.5f
    cardTexture: arrower
    mapTexture: arrower
    stuffTexture: arrowerStuff
    attackTexture: arrow
  - #
    cardType: "yys"
    rarity: S
    attackPower: 3
    attackRange: 120f
    maxAttackCount: 2
    fireRate: 0.5f
    cardTexture: yys
    mapTexture: yys
    stuffTexture: yysStuff
    attackTexture: fan
  - #
    cardType: "saber"
    rarity: SR
    attackPower: 5
    attackRange: 120f
    maxAttackCount: 3
    fireRate: 0.5f
    cardTexture: saber
    mapTexture: saber
    stuffTexture: saberStuff
    attackTexture: whiteAttack
  - #
    cardType: "swordSaint"
    rarity: SSR
    attackPower: 10
    attackRange: 300f
    maxAttackCount: 3
    fireRate: 0.5f
    cardTexture: swordSaint
    mapTexture: swordSaint
    stuffTexture: swordSaintStuff
    attackTexture: arrow
  - #
    cardType: "necromancer"
    rarity: SSR
    attackPower: 5
    attackRange: 200f
    maxAttackCount: 3
    fireRate: 0.5f
    cardTexture: necromancer
    mapTexture: necromancer
    stuffTexture: necromancerStuff
    attackTexture: necromancerAttack