cardTypeConfigs:
- {cardType: arrower, rarity: N, attackPower: 1, attackRange: 100f, maxAttackCount: 2,
  fireRate: 0.5f, cardTexture: arrower, mapTexture: arrower, stuffTexture: arrowerStuff,
  attackTexture: arrow}
- {cardType: whiteTiger, rarity: N, attackPower: 3, attackRange: 120f, maxAttackCount: 2,
  fireRate: 0.5f, cardTexture: whiteTiger, mapTexture: whiteTiger, stuffTexture: whiteTigerStuff,
  attackTexture: whiteAttack}
- {cardType: prosperityGirl, rarity: S, attackPower: 0, attackRange: 1000f, maxAttackCount: 2,
  fireRate: 0.5f, cardTexture: prosperityGirl, mapTexture: prosperityGirl, stuffTexture: prosperityGirlStuff,
  attackTexture: whiteAttack}
- {cardType: blackTortoise, rarity: S, attackPower: 1, attackRange: 100f, maxAttackCount: 2,
  fireRate: 0.5f, cardTexture: blackTortoise, mapTexture: blackTortoise, stuffTexture: blackTortoiseStuff,
  attackTexture: blackTortoiseAttack}
- {cardType: vermilion, rarity: S, attackPower: 1, attackRange: 100f, maxAttackCount: 2,
  fireRate: 0.5f, cardTexture: vermilion, mapTexture: vermilion, stuffTexture: vermilionStuff,
  attackTexture: vermilionAttack}
- {cardType: yys, rarity: S, attackPower: 4, attackRange: 120f, maxAttackCount: 2,
  fireRate: 0.5f, cardTexture: yys, mapTexture: yys, stuffTexture: yysStuff, attackTexture: fan}
- {cardType: azureDragon, rarity: SR, attackPower: 3, attackRange: 120f, maxAttackCount: 2,
  fireRate: 0.5f, cardTexture: azureDragon, mapTexture: azureDragon, stuffTexture: azureDragonStuff,
  attackTexture: dragonAttack}
- {cardType: saber, rarity: SR, attackPower: 5, attackRange: 120f, maxAttackCount: 3,
  fireRate: 0.5f, cardTexture: saber, mapTexture: saber, stuffTexture: saberStuff,
  attackTexture: whiteAttack}
- {cardType: swordSaint, rarity: SSR, attackPower: 10, attackRange: 300f, maxAttackCount: 3,
  fireRate: 0.5f, cardTexture: swordSaint, mapTexture: swordSaint, stuffTexture: swordSaintStuff,
  attackTexture: saintSword}
- {cardType: necromancer, rarity: SSR, attackPower: 6, attackRange: 200f, maxAttackCount: 3,
  fireRate: 0.5f, cardTexture: necromancer, mapTexture: necromancer, stuffTexture: necromancerStuff,
  attackTexture: necromancerAttack}
