
# 敌人加载配置列表，每个元素代表一个敌人的加载配置
enemyLoadConfigs:
  - # 1.0
    enemyType: saberOne
    enemyName: "Enemy 1.0"
    loadTime: 4.0
  - # 2.0
    enemyType: minion
    enemyName: "Enemy 2.0"
    loadTime: 6.0
  - # 3.0
    enemyType: ironcladGeneral
    enemyName: "ironcladGeneral 3.0"
    loadTime: 8.0
  - # 4.0
    enemyType: minion
    enemyName: "minion 4.0"
    loadTime: 10.0
  - # 5.0
    enemyType: minion
    enemyName: "minion 5.0"
    loadTime: 12.0
  - # 6.0
    enemyType: ironcladGeneral
    enemyName: "ironcladGeneral 6.0"
    loadTime: 14.0
  - # 7.0
    enemyType: archerOne
    enemyName: "archerOne 7.0"
    loadTime: 16.0
  - # 8.0
    enemyType: archerOne
    enemyName: "archerOne 8.0"
    loadTime: 18.0
  - # 9.0
    enemyType: stoneGuardian
    enemyName: "stoneGuardian 9.0"
    loadTime: 20.0
  - # 10.0
    enemyType: stoneGuardian
    enemyName: "stoneGuardian 10.0"
    loadTime: 22.0
  - # 11.0
    enemyType: paperPuppet
    enemyName: "paperPuppet 11.0"
    loadTime: 24.0
  - # 12.0
    enemyType: paperPuppet
    enemyName: "paperPuppet 12.0"
    loadTime: 26.0
  - # 13.0
    enemyType: thunderRoc
    enemyName: "Enemy 13.0"
    loadTime: 28.0
  - # 14.0
    enemyType: thunderRoc
    enemyName: "Enemy 14.0"
    loadTime: 30.0
  - # 15.0
    enemyType: Qilin
    enemyName: "Enemy 15.0"
    loadTime: 32.0
  - # 16.0
    enemyType: Qilin
    enemyName: "Enemy 16.0"
    loadTime: 34.0
  - # 17.0
    enemyType: foxSpirit
    enemyName: "Enemy 17.0"
    loadTime: 36.0
  - # 18.0
    enemyType: foxSpirit
    enemyName: "Enemy 18.0"
    loadTime: 38.0
  - # 19.0
    enemyType: Taotie
    enemyName: "Taotie 19.0"
    loadTime: 40.0
  - # 20.0
    enemyType: Taotie
    enemyName: "Taotie 20.0"
    loadTime: 42.0
  - # 21.0
    enemyType: saberOne
    enemyName: "Enemy 21.0"
    loadTime: 44.0
  - # 22.0
    enemyType: saberOne
    enemyName: "Enemy 22.0"
    loadTime: 46.0
  - # 23.0
    enemyType: saberOne
    enemyName: "Enemy 23.0"
    loadTime: 48.0
  - # 24.0
    enemyType: saberOne
    enemyName: "Enemy 24.0"
    loadTime: 50.0
  - # 25.0
    enemyType: saberOne
    enemyName: "Enemy 25.0"
    loadTime: 52.0
  - # 26.0
    enemyType: saberOne
    enemyName: "Enemy 26.0"
    loadTime: 54.0
  - # 27.0
    enemyType: saberOne
    enemyName: "Enemy 27.0"
    loadTime: 56.0
  - # 28.0
    enemyType: saberOne
    enemyName: "Enemy 28.0"
    loadTime: 58.0
  - # 29.0
    enemyType: saberOne
    enemyName: "Enemy 29.0"
    loadTime: 60.0
  - # 30.0
    enemyType: saberOne
    enemyName: "Enemy 30.0"
    loadTime: 62.0
  - # 31.0
    enemyType: saberOne
    enemyName: "Enemy 31.0"
    loadTime: 64.0
  - # 32.0
    enemyType: saberOne
    enemyName: "Enemy 32.0"
    loadTime: 66.0
  - # 33.0
    enemyType: saberOne
    enemyName: "Enemy 33.0"
    loadTime: 68.0
  - # 34.0
    enemyType: saberOne
    enemyName: "Enemy 34.0"
    loadTime: 70.0
  - # 35.0
    enemyType: saberOne
    enemyName: "Enemy 35.0"
    loadTime: 72.0
  - # 36.0
    enemyType: saberOne
    enemyName: "Enemy 36.0"
    loadTime: 74.0
  - # 37.0
    enemyType: saberOne
    enemyName: "Enemy 37.0"
    loadTime: 76.0
  - # 38.0
    enemyType: saberOne
    enemyName: "Enemy 38.0"
    loadTime: 78.0
  - # 39.0
    enemyType: saberOne
    enemyName: "Enemy 39.0"
    loadTime: 80.0
  - # 40.0
    enemyType: saberOne
    enemyName: "Enemy 40.0"
    loadTime: 82.0
  - # 41.0
    enemyType: saberOne
    enemyName: "Enemy 41.0"
    loadTime: 84.0
  - # 42.0
    enemyType: saberOne
    enemyName: "Enemy 42.0"
    loadTime: 86.0
  - # 43.0
    enemyType: saberOne
    enemyName: "Enemy 43.0"
    loadTime: 88.0
  - # 44.0
    enemyType: saberOne
    enemyName: "Enemy 44.0"
    loadTime: 90.0
  - # 45.0
    enemyType: saberOne
    enemyName: "Enemy 45.0"
    loadTime: 92.0
  - # 46.0
    enemyType: saberOne
    enemyName: "Enemy 46.0"
    loadTime: 94.0
  - # 47.0
    enemyType: saberOne
    enemyName: "Enemy 47.0"
    loadTime: 96.0
  - # 48.0
    enemyType: saberOne
    enemyName: "Enemy 48.0"
    loadTime: 98.0
  - # 49.0
    enemyType: saberOne
    enemyName: "Enemy 49.0"
    loadTime: 100.0
  - # 50.0
    enemyType: saberOne
    enemyName: "Enemy 50.0"
    loadTime: 102.0
  - # 51.0
    enemyType: saberOne
    enemyName: "Enemy 51.0"
    loadTime: 104.0
  - # 52.0
    enemyType: saberOne
    enemyName: "Enemy 52.0"
    loadTime: 106.0
  - # 53.0
    enemyType: saberOne
    enemyName: "Enemy 53.0"
    loadTime: 108.0
  - # 54.0
    enemyType: saberOne
    enemyName: "Enemy 54.0"
    loadTime: 110.0
  - # 55.0
    enemyType: saberOne
    enemyName: "Enemy 55.0"
    loadTime: 112.0
  - # 56.0
    enemyType: saberOne
    enemyName: "Enemy 56.0"
    loadTime: 114.0
  - # 57.0
    enemyType: saberOne
    enemyName: "Enemy 57.0"
    loadTime: 116.0
  - # 58.0
    enemyType: saberOne
    enemyName: "Enemy 58.0"
    loadTime: 118.0
  - # 59.0
    enemyType: saberOne
    enemyName: "Enemy 59.0"
    loadTime: 120.0
  - # 60.0
    enemyType: saberOne
    enemyName: "Enemy 60.0"
    loadTime: 122.0
  - # 61.0
    enemyType: saberOne
    enemyName: "Enemy 61.0"
    loadTime: 124.0
  - # 62.0
    enemyType: saberOne
    enemyName: "Enemy 62.0"
    loadTime: 126.0
  - # 63.0
    enemyType: saberOne
    enemyName: "Enemy 63.0"
    loadTime: 128.0
  - # 64.0
    enemyType: saberOne
    enemyName: "Enemy 64.0"
    loadTime: 130.0
  - # 65.0
    enemyType: saberOne
    enemyName: "Enemy 65.0"
    loadTime: 132.0
  - # 66.0
    enemyType: saberOne
    enemyName: "Enemy 66.0"
    loadTime: 134.0
  - # 67.0
    enemyType: saberOne
    enemyName: "Enemy 67.0"
    loadTime: 136.0
  - # 68.0
    enemyType: saberOne
    enemyName: "Enemy 68.0"
    loadTime: 138.0
  - # 69.0
    enemyType: saberOne
    enemyName: "Enemy 69.0"
    loadTime: 140.0
  - # 70.0
    enemyType: saberOne
    enemyName: "Enemy 70.0"
    loadTime: 142.0
  - # 71.0
    enemyType: saberOne
    enemyName: "Enemy 71.0"
    loadTime: 144.0
  - # 72.0
    enemyType: saberOne
    enemyName: "Enemy 72.0"
    loadTime: 146.0
  - # 73.0
    enemyType: saberOne
    enemyName: "Enemy 73.0"
    loadTime: 148.0
  - # 74.0
    enemyType: saberOne
    enemyName: "Enemy 74.0"
    loadTime: 150.0
  - # 75.0
    enemyType: saberOne
    enemyName: "Enemy 75.0"
    loadTime: 152.0
  - # 76.0
    enemyType: saberOne
    enemyName: "Enemy 76.0"
    loadTime: 154.0
  - # 77.0
    enemyType: saberOne
    enemyName: "Enemy 77.0"
    loadTime: 156.0
  - # 78.0
    enemyType: saberOne
    enemyName: "Enemy 78.0"
    loadTime: 158.0
  - # 79.0
    enemyType: saberOne
    enemyName: "Enemy 79.0"
    loadTime: 160.0
  - # 80.0
    enemyType: saberOne
    enemyName: "Enemy 80.0"
    loadTime: 162.0
  - # 81.0
    enemyType: saberOne
    enemyName: "Enemy 81.0"
    loadTime: 164.0
  - # 82.0
    enemyType: saberOne
    enemyName: "Enemy 82.0"
    loadTime: 166.0
  - # 83.0
    enemyType: saberOne
    enemyName: "Enemy 83.0"
    loadTime: 168.0
  - # 84.0
    enemyType: saberOne
    enemyName: "Enemy 84.0"
    loadTime: 170.0
  - # 85.0
    enemyType: saberOne
    enemyName: "Enemy 85.0"
    loadTime: 172.0
  - # 86.0
    enemyType: saberOne
    enemyName: "Enemy 86.0"
    loadTime: 174.0
  - # 87.0
    enemyType: saberOne
    enemyName: "Enemy 87.0"
    loadTime: 176.0
  - # 88.0
    enemyType: saberOne
    enemyName: "Enemy 88.0"
    loadTime: 178.0
  - # 89.0
    enemyType: saberOne
    enemyName: "Enemy 89.0"
    loadTime: 180.0
  - # 90.0
    enemyType: saberOne
    enemyName: "Enemy 90.0"
    loadTime: 182.0
  - # 91.0
    enemyType: saberOne
    enemyName: "Enemy 91.0"
    loadTime: 184.0
  - # 92.0
    enemyType: saberOne
    enemyName: "Enemy 92.0"
    loadTime: 186.0
  - # 93.0
    enemyType: saberOne
    enemyName: "Enemy 93.0"
    loadTime: 188.0
  - # 94.0
    enemyType: saberOne
    enemyName: "Enemy 94.0"
    loadTime: 190.0
  - # 95.0
    enemyType: saberOne
    enemyName: "Enemy 95.0"
    loadTime: 192.0
  - # 96.0
    enemyType: saberOne
    enemyName: "Enemy 96.0"
    loadTime: 194.0
  - # 97.0
    enemyType: saberOne
    enemyName: "Enemy 97.0"
    loadTime: 196.0
  - # 98.0
    enemyType: saberOne
    enemyName: "Enemy 98.0"
    loadTime: 198.0
  - # 99.0
    enemyType: saberOne
    enemyName: "Enemy 99.0"
    loadTime: 200.0
  - # 100.0
    enemyType: saberOne
    enemyName: "Enemy 100.0"
    loadTime: 202.0
  - # 101.0
    enemyType: saberOne
    enemyName: "Enemy 101.0"
    loadTime: 204.0
  - # 102.0
    enemyType: saberOne
    enemyName: "Enemy 102.0"
    loadTime: 206.0
  - # 103.0
    enemyType: saberOne
    enemyName: "Enemy 103.0"
    loadTime: 208.0
  - # 104.0
    enemyType: saberOne
    enemyName: "Enemy 104.0"
    loadTime: 210.0
  - # 105.0
    enemyType: saberOne
    enemyName: "Enemy 105.0"
    loadTime: 212.0
  - # 106.0
    enemyType: saberOne
    enemyName: "Enemy 106.0"
    loadTime: 214.0
  - # 107.0
    enemyType: saberOne
    enemyName: "Enemy 107.0"
    loadTime: 216.0
  - # 108.0
    enemyType: saberOne
    enemyName: "Enemy 108.0"
    loadTime: 218.0
  - # 109.0
    enemyType: saberOne
    enemyName: "Enemy 109.0"
    loadTime: 220.0