
# 敌人加载配置列表，每个元素代表一个敌人的加载配置
enemyLoadConfigs:
  - # 1.0
    enemyType: saberOne
    enemyName: "Enemy 1.0"
    loadTime: 4.0
  - # 2.0
    enemyType: saberOne
    enemyName: "Enemy 2.0"
    loadTime: 6.0
  - # 3.0
    enemyType: saberOne
    enemyName: "Enemy 3.0"
    loadTime: 12.0